### ISSUE TITLE
How to change voice?

### ISSUE THREAD

**Issue by Garakros** [zbears/pyvona#22]
v.voice_name("English, American, Justin")

Doesn't work gives following error:

Traceback (most recent call last):
  File "D:/Python/Playground 3+/pyvona ivona.py", line 5, in <module>
    v.voice_name("English, American, Salli")
TypeError: 'str' object is not callable

v.list_voices() gives following error:

Traceback (most recent call last):
  File "D:/Python/Playground 3+/pyvona ivona.py", line 6, in <module>
    str(v.list_voices())
  File "C:\Python35\lib\site-packages\pyvona.py", line 149, in list_voices
    return json.loads(r.content)
  File "C:\Python35\lib\json__init__.py", line 312, in loads
    s.**class**.**name**))
TypeError: the JSON object must be str, not 'bytes'

**Comment by Jbithell** [comment]
Do you mean `v.voice_name = "Salli"`?

**Comment by zbears** [comment]
Thanks for answering this one.
