### ISSUE TITLE
Python 3 on Windows 7 install issue

### ISSUE THREAD

**Issue by virgiliu** [zbears/pyvona#7]
Anything I can do to install pyvona on Windows 7 and Python 3.4.1?
When I try to install via pip I get this:

```
C:\Users\v>pip install pyvona
Downloading/unpacking pyvona
  Downloading pyvona-0.22.tar.gz
  Running setup.py (path:C:\Users\v\AppData\Local\Temp\pip_build_v\pyvona\setup.py) egg_info for package pyvona
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "C:\Users\v\AppData\Local\Temp\pip_build_v\pyvona\setup.py", line 8
        print "Welcome to Pyvona setup. Installing Pyvona..."
                                                            ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "C:\Users\v\AppData\Local\Temp\pip_build_v\pyvona\setup.py", line 8

    print "Welcome to Pyvona setup. Installing Pyvona..."

                                                    ^

SyntaxError: invalid syntax

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in C:\Users\v\AppData\Local\Temp\pip_build_v\pyvona
Storing debug log for failure in C:\Users\v\pip\pip.log

C:\Users\v>python --version
Python 3.4.1
```

**Comment by zbears** [comment]
Thanks for catching that error. Simple Python 2 print statement was causing the problem. It should be fixed now.
