### ISSUE TITLE
Unicode related error when speaking using Python 3

### ISSUE THREAD

**Issue by virgiliu** [zbears/pyvona#8]
```
>>> import pyvona
>>> v = pyvona.create_voice('REDACTED', 'REDACTED')
>>> v.speak('Hello world')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\lib\site-packages\pyvona.py", line 120, in speak
    self.fetch_voice_ogg(text_to_speak, temp_fname)
  File "C:\Python34\lib\site-packages\pyvona.py", line 94, in fetch_voice_ogg
    self.fetch_voice(text_to_speak, filename)
  File "C:\Python34\lib\site-packages\pyvona.py", line 105, in fetch_voice
vself._generate_payload(text_to_speak), self._region, self._host)
  File "C:\Python34\lib\site-packages\pyvona.py", line 166, in _send_amazon_auth_packet_v4
vpayload_hash = self._sha_hash(request_parameters)
  File "C:\Python34\lib\site-packages\pyvona.py", line 211, in _sha_hash
    return hashlib.sha256(to_hash).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
```

**Comment by zbears** [comment]
Fixed and tested with Python 3. Thanks again for finding the errors.
